
import { MenuItem } from "@/features/menu/types";

export const MOCK_MENU_ITEMS: MenuItem[] = [
    {
        id: '1',
        name: 'Classic Smash Burger',
        description: 'Juicy double-smashed beef patties with aged cheddar, caramelized onions, pickles, and our signature house sauce on a brioche bun.',
        price: 1299,
        category: 'Mains',
        image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=500&q=60',
        images: [
            'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?auto=format&fit=crop&w=800&q=80',
        ],
        active: true,
        dietary_tags: [],
        rating: 4.8,
        review_count: 124,
        prep_time: 20,
        serves: 1,
        calories: 680,
        featured: true,
        benefits: ['crowd favorite', 'quick prep']
    },
    {
        id: '2',
        name: 'Rainbow Buddha Bowl',
        description: 'Protein-packed quinoa with crispy roasted chickpeas, creamy avocado, massaged kale, pickled red cabbage, and lemon-tahini drizzle.',
        price: 1450,
        category: 'Mains',
        image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=500&q=60',
        images: [
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
        ],
        active: true,
        dietary_tags: ['vegan', 'gluten-free'],
        rating: 4.9,
        review_count: 89,
        prep_time: 25,
        serves: 1,
        calories: 420,
        featured: true,
        seasonal: 'winter',
        benefits: ['high protein', 'meal prep friendly']
    },
    {
        id: '3',
        name: 'Spicy Tuna Tartare',
        description: 'Sushi-grade tuna hand-diced with sriracha aioli, sesame, crispy shallots, and wonton chips. Light, fresh, and boldly flavored.',
        price: 899,
        category: 'Appetizers',
        image_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=500&q=60',
        images: [
            'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
        ],
        active: true,
        dietary_tags: ['gluten-free'],
        rating: 4.7,
        review_count: 56,
        prep_time: 15,
        serves: 2,
        calories: 280,
        benefits: ['shareable', 'light bite']
    },
    {
        id: '4',
        name: 'Molten Chocolate Lava Cake',
        description: 'Warm, rich chocolate cake with a gooey molten center, dusted with cocoa and served with vanilla bean gelato. Pure indulgence.',
        price: 950,
        category: 'Desserts',
        image_url: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=500&q=60',
        images: [
            'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=800&q=80',
        ],
        active: true,
        dietary_tags: ['vegetarian'],
        rating: 4.9,
        review_count: 201,
        prep_time: 12,
        serves: 1,
        calories: 520,
        featured: true,
        benefits: ['date night', 'decadent']
    },
    {
        id: '5',
        name: 'Classic Caesar Salad',
        description: 'Crisp romaine hearts, shaved parmesan, garlicky croutons, and creamy house-made caesar dressing. Add grilled chicken or shrimp.',
        price: 1099,
        category: 'Appetizers',
        image_url: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=500&q=60',
        images: [
            'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=800&q=80',
        ],
        active: true,
        dietary_tags: [],
        rating: 4.5,
        review_count: 78,
        prep_time: 10,
        serves: 2,
        calories: 340,
        benefits: ['classic', 'customizable']
    },
    {
        id: '6',
        name: 'Honey Glazed Salmon',
        description: 'Wild-caught salmon fillet with honey-soy glaze, served over jasmine rice with sautéed seasonal vegetables. Heart-healthy and satisfying.',
        price: 1899,
        category: 'Mains',
        image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=500&q=60',
        images: [
            'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80',
        ],
        active: true,
        dietary_tags: ['gluten-free'],
        rating: 4.8,
        review_count: 143,
        prep_time: 30,
        serves: 1,
        calories: 580,
        seasonal: 'winter',
        benefits: ['omega-3 rich', 'elegant']
    },
    {
        id: '7',
        name: 'Truffle Mushroom Risotto',
        description: 'Creamy arborio rice slow-cooked with wild mushrooms, white wine, parmesan, and finished with black truffle oil. Pure comfort.',
        price: 1650,
        category: 'Mains',
        image_url: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=500&q=60',
        images: [
            'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=800&q=80',
        ],
        active: true,
        dietary_tags: ['vegetarian'],
        rating: 4.7,
        review_count: 92,
        prep_time: 35,
        serves: 2,
        calories: 620,
        seasonal: 'winter',
        featured: true,
        benefits: ['comfort food', 'date night']
    },
    {
        id: '8',
        name: 'Fresh Fruit Tart',
        description: 'Buttery shortbread crust filled with vanilla pastry cream and topped with seasonal berries and apricot glaze. Light and beautiful.',
        price: 850,
        category: 'Desserts',
        image_url: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=500&q=60',
        images: [
            'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=800&q=80',
        ],
        active: true,
        dietary_tags: ['vegetarian'],
        rating: 4.6,
        review_count: 67,
        prep_time: 15,
        serves: 1,
        calories: 380,
        seasonal: 'summer',
        benefits: ['refreshing', 'instagram worthy']
    }
]
