
import { MenuItem } from "@/features/menu/types";

export const MOCK_MENU_ITEMS: MenuItem[] = [
    // WARM COOKIES
    {
        id: '1',
        name: 'Chocolate Chip',
        description: 'Our signature cookie packed with semi-sweet chocolate chips. Baked fresh and served warm.',
        price: 199,
        category: 'warm',
        image_url: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 4.9,
        review_count: 524,
        prep_time: 15,
        serves: 1,
        calories: 180,
        featured: true,
        benefits: ['classic', 'bestseller']
    },
    {
        id: '2',
        name: 'Snickerdoodle',
        description: 'Buttery sugar cookie rolled in cinnamon sugar. A classic favorite.',
        price: 199,
        category: 'warm',
        image_url: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 4.8,
        review_count: 312,
        prep_time: 15,
        serves: 1,
        calories: 170,
        featured: true,
        benefits: ['cinnamon lover']
    },
    {
        id: '3',
        name: 'White Chocolate Macadamia',
        description: 'Rich white chocolate chunks and roasted macadamia nuts in a buttery cookie.',
        price: 225,
        category: 'warm',
        image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: ['contains-nuts'],
        rating: 4.9,
        review_count: 405,
        prep_time: 15,
        serves: 1,
        calories: 210,
        benefits: ['premium', 'nutty']
    },

    // PACKS
    {
        id: '4',
        name: 'The Classic Dozen',
        description: 'A mix of our top sellers: 6 Chocolate Chip, 3 Snickerdoodle, 3 Oatmeal Raisin.',
        price: 2200,
        category: 'packs',
        image_url: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 5.0,
        review_count: 156,
        prep_time: 20,
        serves: 12,
        calories: 2200,
        featured: true,
        benefits: ['value', 'shareable']
    },
    {
        id: '5',
        name: 'Party Pack',
        description: '24 cookies of your choice. Perfect for office parties or gatherings.',
        price: 4000,
        category: 'packs',
        image_url: 'https://images.unsplash.com/photo-1600431562968-ef980c92f0ce?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1600431562968-ef980c92f0ce?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 4.9,
        review_count: 89,
        prep_time: 25,
        serves: 24,
        calories: 4400,
        benefits: ['gathering', 'value']
    },

    // FROZEN DOUGH
    {
        id: '6',
        name: 'Chocolate Chip Dough (Frozen)',
        description: 'Bake at home! 12 pre-portioned balls of our famous cookie dough.',
        price: 1600,
        category: 'frozen',
        image_url: 'https://images.unsplash.com/photo-1627834377411-8da5f4f09de8?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1627834377411-8da5f4f09de8?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 4.7,
        review_count: 45,
        prep_time: 0,
        serves: 12,
        calories: 1800,
        benefits: ['bake at home', 'fun']
    },

    // COOKIE PIES
    {
        id: '7',
        name: 'Deep Dish Cookie Pie',
        description: 'A 9-inch deep dish chocolate chip cookie cake. Decorated with frosting.',
        price: 2499,
        category: 'pie',
        image_url: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 4.8,
        review_count: 78,
        prep_time: 45,
        serves: 8,
        calories: 3200,
        featured: true,
        benefits: ['celebration', 'sharable']
    },

    // BROWNIES
    {
        id: '8',
        name: 'Fudge Brownie',
        description: 'Decadent, fudgy chocolate brownie with a crackly top.',
        price: 250,
        category: 'brownies',
        image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 4.9,
        review_count: 112,
        prep_time: 15,
        serves: 1,
        calories: 350,
        benefits: ['rich', 'chocolatey']
    },

    // ICE CREAM
    {
        id: '9',
        name: 'Vanilla Bean Pint',
        description: 'Premium vanilla bean ice cream. The perfect companion to warm cookies.',
        price: 699,
        category: 'ice-cream',
        image_url: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: ['gluten-free'],
        rating: 4.6,
        review_count: 88,
        prep_time: 5,
        serves: 4,
        calories: 800,
        benefits: ['creamy', 'pairing']
    },

    // DRINKS
    {
        id: '10',
        name: 'Cold Milk',
        description: 'Ice cold whole milk. Essential for cookie dipping.',
        price: 250,
        category: 'drinks',
        image_url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: ['gluten-free'],
        rating: 4.8,
        review_count: 205,
        prep_time: 5,
        serves: 1,
        calories: 150,
        benefits: ['classic', 'essential']
    },

    // OCCASION ITEMS (Mapped via logic or separate tags in real app, but for now specific items)
    {
        id: '11',
        name: 'Birthday Cake Cookie',
        description: 'Sugar cookie with sprinkles and white chocolate chips.',
        price: 225,
        category: 'warm',
        image_url: 'https://images.unsplash.com/photo-1557310717-d6bea9f36682?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1557310717-d6bea9f36682?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 4.9,
        review_count: 67,
        prep_time: 15,
        serves: 1,
        calories: 190,
        seasonal: 'birthday',
        benefits: ['celebration', 'colorful']
    },
    {
        id: '12',
        name: 'Thank You Box',
        description: 'A dozen cookies in a beautiful "Thank You" gift box.',
        price: 2800,
        category: 'packs',
        image_url: 'https://images.unsplash.com/photo-1549488344-c7079f913d56?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1549488344-c7079f913d56?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 5.0,
        review_count: 45,
        prep_time: 20,
        serves: 12,
        calories: 2200,
        seasonal: 'thank-you',
        benefits: ['gifting', 'gratitude']
    },
    {
        id: '13',
        name: 'Heart Shaped Cookie',
        description: 'Large heart shaped sugar cookie with pink frosting.',
        price: 350,
        category: 'warm',
        image_url: 'https://images.unsplash.com/photo-1516154656463-71a62d0b5e78?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1516154656463-71a62d0b5e78?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: [],
        rating: 4.8,
        review_count: 120,
        prep_time: 15,
        serves: 1,
        calories: 250,
        seasonal: 'love',
        benefits: ['romance', 'special']
    }
]
