
import { MenuItem } from "@/features/menu/types";

export const MOCK_MENU_ITEMS: MenuItem[] = [
    // ORGANIC CAKES
    {
        id: '1',
        name: 'The Signature Blessing',
        description: 'Our crown jewel. A triple-layered organic chocolate masterpiece crafted with heritage cocoa and celestial velvet cream.',
        price: 8500,
        category: 'organic-cakes',
        image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=90'],
        active: true,
        dietary_tags: ['organic', 'premium'],
        rating: 5.0,
        review_count: 850,
        prep_time: 60,
        serves: 12,
        calories: 450,
        featured: true,
        benefits: ['heritage-cocoa', 'organic-certified', 'hand-crafted']
    },
    {
        id: '2',
        name: 'Lavender Dream Bliss',
        description: 'An ethereal sponge infused with organic French lavender and vanilla bean. Light as a morning prayer.',
        price: 7200,
        category: 'organic-cakes',
        image_url: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=1200&q=90'],
        active: true,
        dietary_tags: ['organic', 'gluten-optional'],
        rating: 4.9,
        review_count: 420,
        prep_time: 45,
        serves: 8,
        calories: 320,
        featured: true,
        benefits: ['french-lavender', 'pure-vanilla', 'low-sugar']
    },
    {
        id: '3',
        name: 'Golden Pecan Radiance',
        description: 'A warm, sun-kissed delight filled with toasted organic pecans and a hint of Canadian maple syrup.',
        price: 6800,
        category: 'organic-cakes',
        image_url: 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=1200&q=90'],
        active: true,
        dietary_tags: ['contains-nuts', 'organic'],
        rating: 4.9,
        review_count: 215,
        prep_time: 45,
        serves: 8,
        calories: 380,
        featured: false,
        benefits: ['toasted-pecans', 'maple-glaze']
    },
    {
        id: '4',
        name: 'Lemon Sunshine Grace',
        description: 'Zesty organic lemons harvest from heritage groves meeting our signature velvet crumb. Pure radiance.',
        price: 6500,
        category: 'organic-cakes',
        image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=90'],
        active: true,
        dietary_tags: ['organic', 'citrus'],
        rating: 5.0,
        review_count: 124,
        prep_time: 45,
        serves: 8,
        calories: 310,
        featured: true,
        benefits: ['cold-pressed-lemon', 'fresh-harvest']
    },
    {
        id: '5',
        name: 'The Mother’s Blessing',
        description: 'Our sacred recipe. Nutrient-dense organic ingredients specifically balanced to support and celebrate new mothers.',
        price: 7800,
        category: 'organic-cakes',
        image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=90'],
        active: true,
        dietary_tags: ['lactation-support', 'organic'],
        rating: 5.0,
        review_count: 562,
        prep_time: 60,
        serves: 10,
        calories: 340,
        featured: true,
        benefits: ['nutrient-dense', 'mom-approved', 'organic-whole-grains']
    },

    // BUNDLES
    {
        id: '6',
        name: 'Family Blessing Bundle',
        description: 'Choice of 2 whole organic cakes. Perfect for gatherings and celebrations.',
        price: 7000,
        category: 'bundles',
        image_url: 'https://images.unsplash.com/photo-1519340333755-56e9c1d04579?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1519340333755-56e9c1d04579?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: ['organic'],
        rating: 5.0,
        review_count: 56,
        prep_time: 45,
        serves: 16,
        calories: 6000,
        featured: false,
        benefits: ['value', 'gathering']
    },
    {
        id: '7',
        name: 'Taste of Abraham Sampler',
        description: '4 mini-cakes (Lemon, Coconut, Chocolate, Pecan) to try them all.',
        price: 4500,
        category: 'bundles',
        image_url: 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=500&q=60',
        images: ['https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=800&q=80'],
        active: true,
        dietary_tags: ['organic'],
        rating: 4.8,
        review_count: 45,
        prep_time: 30,
        serves: 4,
        calories: 1200,
        featured: true,
        benefits: ['variety', 'gift']
    }
]
