-- Create daily_menu table
create table public.daily_menu (
  id bigint generated by default as identity primary key,
  name text not null,
  sold_out boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.daily_menu enable row level security;

-- Create policies
create policy "Allow public read access" on public.daily_menu
  for select using (true);

create policy "Allow admin insert" on public.daily_menu
  for insert with check (
    exists (select 1 from public.users where id = auth.uid() and role = 'admin')
  );

create policy "Allow admin update" on public.daily_menu
  for update using (
    exists (select 1 from public.users where id = auth.uid() and role = 'admin')
  );

create policy "Allow admin delete" on public.daily_menu
  for delete using (
    exists (select 1 from public.users where id = auth.uid() and role = 'admin')
  );
